# Generated by Django 5.2.8 on 2025-12-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('data_entry', 'Data Entry (Admin)'), ('sales', 'Sales Agent'), ('investor', 'Investor')], default='sales', max_length=20),
        ),
    ]
