# leads/idiomas.py

DICCIONARIO = {
    'es': {
        'nav_prospectos': 'Prospectos',
        'nav_salir': 'Salir',
        'titulo_lista': 'Lista de Prospectos',
        'btn_nuevo': '＋ Nuevo Cliente',
        'btn_limpiar': 'Limpiar Filtros',
        'th_nombre': 'Nombre',
        'th_pais': 'País',
        'th_interes': 'Interés',
        'th_estado': 'Estado',
        'th_ingreso': 'Fecha Ingreso',
        'th_contacto': 'Último Contacto',
        'th_accion': 'Acciones',
        'sin_registros': 'No hay prospectos registrados.',
        'filtro_pais': '🌎 Todos los Países',
        'filtro_estado': '📊 Todos los Estados',
        'estado_interesado': '🟢 Interesados',
        'estado_pendiente': '🟡 Pendientes',
        'estado_no_contactado': '🔴 No Contactados',
        'login_titulo': 'Acceso CRM',
        'login_usuario': 'Usuario',
        'login_pass': 'Contraseña',
        'login_btn': 'Ingresar',
        'form_titulo_crear': 'Nuevo Prospecto',
        'form_titulo_editar': 'Editar Prospecto',
        'btn_guardar': 'Guardar',
        'btn_cancelar': 'Cancelar',
        # --- NUEVAS ETIQUETAS PARA EL FORMULARIO ---
        'lbl_nombre': 'Nombre Completo',
        'lbl_pais': 'País',
        'lbl_email': 'Correo Electrónico',
        'lbl_telefono': 'Teléfono',
        'lbl_presupuesto': 'Presupuesto / Interés',
        'lbl_estado': 'Estado de Gestión',
        'lbl_notas': 'Notas / Bitácora',
        # -------------------------------------------
        'db_no_contactado': 'No Contactado',
        'db_pendiente': 'Pendiente',
        'db_interesado': 'Interesado',
        'db_no_interesado': 'No Interesado',
        'db_10M': '10 Millones (Alto)',
        'db_6M': '6 Millones (Medio)',
        'db_4M': '4 Millones (Bajo)',
    },
    'en': {
        'nav_prospectos': 'Leads',
        'nav_salir': 'Logout',
        'titulo_lista': 'Leads List',
        'btn_nuevo': '＋ New Client',
        'btn_limpiar': 'Clear Filters',
        'th_nombre': 'Name',
        'th_pais': 'Country',
        'th_interes': 'Budget',
        'th_estado': 'Status',
        'th_ingreso': 'Date Added',
        'th_contacto': 'Last Contact',
        'th_accion': 'Actions',
        'sin_registros': 'No leads found.',
        'filtro_pais': '🌎 All Countries',
        'filtro_estado': '📊 All Statuses',
        'estado_interesado': '🟢 Interested',
        'estado_pendiente': '🟡 Pending',
        'estado_no_contactado': '🔴 Not Contacted',
        'login_titulo': 'CRM Login',
        'login_usuario': 'Username',
        'login_pass': 'Password',
        'login_btn': 'Sign In',
        'form_titulo_crear': 'New Lead',
        'form_titulo_editar': 'Edit Lead',
        'btn_guardar': 'Save Changes',
        'btn_cancelar': 'Cancel',
        # --- NEW FORM LABELS ---
        'lbl_nombre': 'Full Name',
        'lbl_pais': 'Country',
        'lbl_email': 'Email Address',
        'lbl_telefono': 'Phone Number',
        'lbl_presupuesto': 'Budget / Interest',
        'lbl_estado': 'Status',
        'lbl_notas': 'Notes / Logs',
        # -----------------------
        'db_no_contactado': 'Not Contacted',
        'db_pendiente': 'Pending',
        'db_interesado': 'Interested',
        'db_no_interesado': 'Not Interested',
        'db_10M': '10 Millions (High)',
        'db_6M': '6 Millions (Mid)',
        'db_4M': '4 Millions (Low)',
    }
}